spring:
  application:
    name: auth-service

keycloak:
  token-url: ${KEYCLOAK_TOKEN_URL:http://keycloak:8080/realms/flowops/protocol/openid-connect/token}
  jwks-url: ${KEYCLOAK_JWKS_URL:http://keycloak:8080/realms/flowops/protocol/openid-connect/certs}
