version: "3.9"
services:
  mongodb:
    image: mongo:6.0
    container_name: pluginservice-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: pluginservice-minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data

  plugin-service:
    build: .
    image: plugin-service:latest
    container_name: plugin-service
    depends_on:
      - mongodb
      - minio
    ports:
      - "${PLUGIN_SERVICE_PORT}:8080"
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

volumes:
  mongo_data:
  minio_data:
